# 基础配置
port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
external-ui: ui

# DNS 配置
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 223.5.5.5
    - 94.140.14.14
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://dns.adguard-dns.com/dns-query

# 代理组（自动选择）
proxy-groups:
  - name: AUTO
    type: url-test
    include-all: true
    exclude-type: direct
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    icon: https://raw.githubusercontent.com/Koolson/Qure/refs/heads/master/IconSet/Color/Speedtest.png

# 规则集提供者
rule-providers:
  adblock:
    url: "https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockmihomo.yaml"
    path: ./rules/adblock.yaml
    behavior: domain
    interval: 86400
    format: yaml
    type: http
    
  private:
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.yaml
    path: ./ruleset/private.yaml
    behavior: domain
    interval: 86400
    format: yaml
    type: http
  
  cn_ip:
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.yaml
    path: ./ruleset/cn_ip.yaml
    behavior: ipcidr
    interval: 86400
    format: yaml
    type: http
  
  cn_domain:
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.yaml
    path: ./ruleset/cn_domain.yaml
    behavior: domain
    interval: 86400
    format: yaml
    type: http  
  
  youtube:
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.yaml
    path: ./ruleset/youtube.yaml
    behavior: domain
    interval: 86400
    format: yaml
    type: http
 
  telegram:
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.yaml
    path: ./ruleset/telegram.yaml
    behavior: domain
    interval: 86400
    format: yaml
    type: http



# 规则引用（按优先级排序）
rules:
  - RULE-SET,adblock,REJECT
  - RULE-SET,youtube,AUTO
  - RULE-SET,telegram,AUTO
  - RULE-SET,private,DIRECT
  - RULE-SET,cn_domain,DIRECT
  - RULE-SET,cn_ip,DIRECT

  - MATCH,AUTO


