# Mihomo 配置文件
# 端口配置
port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7893
mixed-port: 7890

# 允许局域网连接
allow-lan: true
bind-address: '*'

# 模式设置
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

# DNS 配置
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 223.5.5.5  # 阿里 DNS
    - 8.8.8.8    # 谷歌 DNS
  nameserver:
    - https://dns.alidns.com/dns-query  # 阿里 DoH
    - https://dns.google/dns-query      # 谷歌 DoH
  fallback:
    - https://dns.google/dns-query      # 谷歌 DoH
    - https://dns.alidns.com/dns-query  # 阿里 DoH
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4


proxy-groups:
  # 手动选择组
  - name: "手动选择"
    type: select
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Server.png
    include-all: true
    exclude-filter: (?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置

  
  # 国内直连组
  - name: "国内直连"
    type: select
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/China.png
    proxies:
      - DIRECT

# 规则集配置
rule-providers:
  private:
    type: http
    behavior: domain
    url: "https://edgeone.gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.yaml"
    path: ./ruleset/private.yaml
    interval: 86400

  cn:
    type: http
    behavior: domain
    url: "https://edgeone.gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.yaml"
    path: ./ruleset/cn.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://edgeone.gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.yaml"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://edgeone.gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.yaml"
    path: ./ruleset/lancidr.yaml
    interval: 86400

# 规则配置
rules:
  # 管理面板直连
  - DOMAIN,clash.razord.top,国内直连
  - DOMAIN,yacd.haishan.me,国内直连
  
  # 私有网络直连（最高优先级）
  - RULE-SET,private,国内直连
  - RULE-SET,lancidr,国内直连
  - GEOIP,LAN,国内直连
  
  # 国内服务直连
  - RULE-SET,cn,国内直连
  - RULE-SET,cncidr,国内直连
  - GEOIP,CN,国内直连
  
  # 兜底规则（除了直连的全部走代理）
  - MATCH,手动选择