proxy-groups:
  # 手动选择分组 - 只包含地区分组和Node分组
  - name: Select
    type: select
    proxies:
      - US
      - Node
      - HK
      - RU
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Final.png

  # Node分组 - 包含所有节点，手动选择，不自动测速
  - name: Node
    type: select
    include-all: true
    exclude-filter: (?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Server.png

  # 美国分组 - 自动测速
  - name: US
    type: url-test
    include-all: true
    filter: (?i)美国|美|US|USA|United States|America|San Francisco|Los Angeles|New York|Chicago|Miami|Dallas|Seattle|Phoenix|Denver|Atlanta
    exclude-filter: (?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/United_States.png

  # 香港分组 - 自动测速
  - name: HK
    type: url-test
    include-all: true
    filter: (?i)香港|港|HK|Hong Kong|HongKong|hongkong|hk
    exclude-filter: (?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Hong_Kong.png

  # 俄罗斯分组 - 自动测速
  - name: RU
    type: url-test
    include-all: true
    filter: (?i)俄罗斯|俄|RU|Russia|Moscow|Saint Petersburg|Novosibirsk|Yekaterinburg
    exclude-filter: (?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Russia.png

  # 国内直连分组
  - name: CN
    type: select
    proxies:
      - DIRECT
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/China.png

  # AI服务分组 - 包含香港、美国和手动选择
  - name: AI
    type: select
    proxies:
      - HK
      - US
      - Select
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/ChatGPT.png

  # Google分组 - 默认香港
  - name: Google
    type: select
    proxies:
      - HK
      - US
      - RU
      - Select
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Google_Search.png

  # 微软分组 - 默认国内直连
  - name: Microsoft
    type: select
    proxies:
      - CN
      - HK
      - US
      - RU
      - Select
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Microsoft.png

  # YouTube分组 - 包含所有地区分组，默认香港
  - name: YouTube
    type: select
    proxies:
      - HK
      - RU
      - US
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png

  # Telegram分组 - 默认香港
  - name: Telegram
    type: select
    proxies:
      - HK
      - US
      - RU
      - Select
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Telegram.png

rule-providers:
  # 私有网络
  private:
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/private.yaml
    path: ./ruleset/private.yaml
    behavior: domain
    interval: 86400
    format: yaml
    type: http

  # 国内域名
  cn_domain:
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/cn.yaml
    path: ./ruleset/cn_domain.yaml
    behavior: domain
    interval: 86400
    format: yaml
    type: http

  # 国内IP
  cn_ip:
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/cn.yaml
    path: ./ruleset/cn_ip.yaml
    behavior: ipcidr
    interval: 86400
    format: yaml
    type: http

  # YouTube规则
  youtube:
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube.yaml
    path: ./ruleset/youtube.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http

  # Telegram规则
  telegram:
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Telegram/Telegram.yaml
    path: ./ruleset/telegram.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http

  # Google规则
  google:
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google//Google_Search.yaml
    path: ./ruleset/google.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http

  # 微软规则 - 国内服务
  microsoft_cn:
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft.yaml
    path: ./ruleset/microsoft_cn.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http

  # AI服务规则
  openai:
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI.yaml
    path: ./ruleset/openai.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http

  claude:
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Claude/Claude.yaml
    path: ./ruleset/claude.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http

  bard:
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/BardAI/BardAI.yaml
    path: ./ruleset/bard.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http

  copilot:
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Copilot/Copilot.yaml
    path: ./ruleset/copilot.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http

  bing:
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Bing/Bing.yaml
    path: ./ruleset/bing.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http

  # 非中国地区域名
  geolocation-!cn:
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/geolocation-!cn.yaml
    path: ./ruleset/geolocation-!cn.yaml
    behavior: domain
    interval: 86400
    format: yaml
    type: http

rules:

  # AI服务
  - "RULE-SET,openai,AI"
  - "RULE-SET,claude,AI"
  - "RULE-SET,bard,AI"
  - "RULE-SET,copilot,AI"
  - "RULE-SET,bing,AI"
  
  # 私有网络直连
  - "RULE-SET,private,DIRECT"
  
  # 国内域名和IP直连
  - "RULE-SET,cn_domain,CN"
  - "RULE-SET,cn_ip,CN"
  
  # YouTube服务
  - "RULE-SET,youtube,YouTube"
  
  # Telegram服务
  - "RULE-SET,telegram,Telegram"
  
  # Google服务
  - "RULE-SET,google,Google"
  
  # 微软服务 - 默认国内直连
  - "RULE-SET,microsoft_cn,Microsoft"
  
  # 非中国地区域名走手动选择
  - "RULE-SET,geolocation-!cn,Select"
  
  # 兜底规则 - 其他所有流量走手动选择
  - "MATCH,Select"
