proxy-groups:
  # 手动选择分组 - 只包含地区分组
  - name: Select
    type: select
    proxies:
      - US
      - RU
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Static.png

  # 美国分组 - 自动测速
  - name: US
    type: url-test
    include-all: true
    filter: (?i)美国|美|US|USA|United States|America|San Francisco|Los Angeles|New York|Chicago|Miami|Dallas|Seattle|Phoenix|Denver|Atlanta
    exclude-filter: GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置
    url: http://detectportal.firefox.com/success.txt
    interval: 300
    tolerance: 200
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/United_States.png

  # 俄罗斯分组 - 自动测速
  - name: RU
    type: url-test
    include-all: true
    filter: (?i)俄罗斯|俄|RU|Russia|Moscow|Saint Petersburg|Novosibirsk|Yekaterinburg
    exclude-filter: GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置
    url: http://detectportal.firefox.com/success.txt
    interval: 300
    tolerance: 200
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Russia.png

  # AI服务分组 - 包含手动选择和美国分组
  - name: AI
    type: select
    proxies:
      - US
      - Select
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/claude.png
  # YouTube分组 - 包含美国和俄罗斯分组，默认俄罗斯
  - name: YouTube
    type: select
    proxies:
      - RU
      - US
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png

  # GitHub分组 - 包含美国和手动选择分组
  - name: GitHub
    type: select
    proxies:
      - US
      - Select
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/GitHub.png

rule-providers:
  # 私有网络
  private:
    url: https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/private.yaml
    path: ./ruleset/private.yaml
    behavior: domain
    interval: 86400
    format: yaml
    type: http

  # 国内域名
  cn_domain:
    url: https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/cn.yaml
    path: ./ruleset/cn_domain.yaml
    behavior: domain
    interval: 86400
    format: yaml
    type: http

  # 国内IP
  cn_ip:
    url: https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/cn.yaml
    path: ./ruleset/cn_ip.yaml
    behavior: ipcidr
    interval: 86400
    format: yaml
    type: http

  # YouTube规则
  youtube:
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube.yaml
    path: ./ruleset/youtube.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http

  # AI服务规则
  openai:
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI.yaml
    path: ./ruleset/openai.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http

  claude:
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Claude/Claude.yaml
    path: ./ruleset/claude.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http

  bard:
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/BardAI/BardAI.yaml
    path: ./ruleset/bard.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http

  copilot:
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Copilot/Copilot.yaml
    path: ./ruleset/copilot.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http

  bing:
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Bing/Bing.yaml
    path: ./ruleset/bing.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http

  # GitHub规则
  github:
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GitHub/GitHub.yaml
    path: ./ruleset/github.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http

  # 非中国地区域名
  geolocation-!cn:
    url: https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/geolocation-!cn.yaml
    path: ./ruleset/geolocation-!cn.yaml
    behavior: domain
    interval: 86400
    format: yaml
    type: http

rules:
  # AI服务
  - RULE-SET,openai,AI
  - RULE-SET,claude,AI
  - RULE-SET,bard,AI
  - RULE-SET,copilot,AI
  - RULE-SET,bing,AI
  
  # 私有网络直连
  - RULE-SET,private,DIRECT
  
  # 国内域名和IP直连
  - RULE-SET,cn_domain,DIRECT
  - RULE-SET,cn_ip,DIRECT
  
  # YouTube服务
  - RULE-SET,youtube,YouTube
  
  # GitHub服务
  - RULE-SET,github,GitHub
  
  # 非中国地区域名走手动选择
  - RULE-SET,geolocation-!cn,Select
  
  # 兜底规则 - 其他所有流量直连
  - MATCH,Select
