port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
external-ui: ui

# DNS 配置
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 223.5.5.5
    - 94.140.14.14
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://dns.adguard-dns.com/dns-query

# 代理组（仅手动）
proxy-groups:
  - name: 手动
    type: select
    include-all: true
    exclude-type: direct
    icon: https://raw.githubusercontent.com/Koolson/Qure/refs/heads/master/IconSet/Color/Speedtest.png

# 规则集提供者
rule-providers:
  LAN:
    type: http
    behavior: classical
    path: ./ruleset/lan.yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.yaml
    interval: 86400

  CN:
    type: http
    behavior: classical
    path: ./ruleset/cn.yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.yaml
    interval: 86400

# 规则引用
rules:
  - RULE-SET,LAN,DIRECT   # 局域网直连
  - RULE-SET,CN,DIRECT    # 国内直连
  - MATCH,手动            # 其他全部走手动代理
