# Mihomo 简化配置文件 - 包含选择、手动和自动分组
port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
external-ui: ui

# DNS 配置
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 223.5.5.5
    - 94.140.14.14
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://dns.adguard-dns.com/dns-query


# 代理组配置
proxy-groups:
  - name: "自动"
    type: url-test
    include-all: true
    exclude-type: direct
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    tolerance: 50
    icon: https://raw.githubusercontent.com/Koolson/Qure/refs/heads/master/IconSet/Color/Speedtest.png



# 规则配置 - 极简规则，所有流量走自动分组
rules:
  # 本地网络直连
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,17.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  
  # 所有其他流量走选择分组
  - MATCH,自动
